### ISSUE TITLE
Creative mode issue

### ISSUE THREAD

**Issue by theshadowake** [SCP002/DropOff#1]
Arrows in creative mode don't work when dropoff is installed, work again if removed.

**Comment by theshadowake** [comment]
https://minecraft.curseforge.com/projects/awakening/issues/216

**Comment by SCP002** [comment]
Oops. Sorry about it, fixed already in dev. environment, but still need a little testing, build and re-upload. 2.8.1 will be available later today. Thanks for contributing!

**Comment by SCP002** [comment]
Fixed with [this commit](https://github.com/SCP002/DropOff/commit/2c4196d39422bb2704a68ae5512e9c3fdbddf029).<br />
Mod file on curseforge is approved now, [grab here](https://minecraft.curseforge.com/projects/dropoff/files/2505738).<br />
Please, test it with your mod pack and check if everything will be fine.<br />
Also, please, backup your mod config file if you have important data stored inside.<br />

**Comment by theshadowake** [comment]
Thanks for the quick fix :)
