### ISSUE TITLE
Config Overwrite On Update

### ISSUE THREAD

**Issue by theshadowake** [SCP002/DropOff#2]
Config file is reset on update loosing all previous settings.

**Comment by SCP002** [comment]
Yep, that's true.
That behavior was old workaround of how forge overwrite config files when developer add new and delete some old properties. I tried to describe it [here](https://github.com/SCP002/DropOff/commit/456201d1d64c70fae060abe44a70e13cefbf1004#diff-1b470a7bcc7ff597d5c39c1ad742950cL23).

However, this is really unfair to delete user data without even asking something.
So, now i fixed it with [this commit](https://github.com/SCP002/DropOff/commit/456201d1d64c70fae060abe44a70e13cefbf1004).
Also removed [this one](https://github.com/SCP002/DropOff/commit/456201d1d64c70fae060abe44a70e13cefbf1004#diff-a32ba02ef019c057e6f5e2fa8c170e50L33). No more chat spam with "Hey you! Check config! Quickly!", lol.

So now config file is just ".\config\dropoff.cfg" and it will stay from version to version without changes. You will only need to edit it **last time**. Because it's new one.

P.S: Please, forgive me if you lost some important data. : - (
P.S.S: Curseforge file is under review now, but you can already grab new build [here](https://github.com/SCP002/DropOff/raw/master/dropoff-1.7.10-2.8.2.jar).

**Comment by theshadowake** [comment]
Thanks for the quick fix again :)
