### ISSUE TITLE
Incompatibility with iron backpacks mod.

### ISSUE THREAD

**Issue by theshadowake** [SCP002/DropOff#3]
https://minecraft.curseforge.com/projects/awakening/issues/236

**Comment by SCP002** [comment]
Good day to you.

TBH, cannot reproduce because I just don't get whichaction from player, exactly, cause this crash. ( ͡°_ʖ ͡°)
However, I reproduced this one: https://github.com/gr8pefish/IronBackpacks/issues/191 (similar to https://github.com/gr8pefish/IronBackpacks/issues/206) on, for example, Awakening. And even without DropOff mod at all.

Maybe it's about this issue?

If yes, then, sadly, it's not DropOff+IronBackPacks related bug and probably we all must wait until January as IronBackpacks owner said in comments to issue. Or fix by our own hands by re-building mod with fix from 'depressed-pho'.

If you can reproduce https://minecraft.curseforge.com/projects/awakening/issues/236 and it's not about https://github.com/gr8pefish/IronBackpacks/issues/191, please, tell me how and what's going on O_o.
I will do my best to fix it.

**Comment by SCP002** [comment]
Issue timed out I guess. Reason: no additional information. Feel free to comment.
